// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pofwbbbxhtarfvfeuzme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvZndiYmJ4aHRhcmZ2ZmV1em1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTAwNzAsImV4cCI6MjA3MjQyNjA3MH0.YDv5eCP4ZcR5Dk38UjnXzGcc5JuqR8Rt58Rhq2xkYOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});